### PR TITLE
Detect changed files for commits on `push` event

### LINKED ISSUE #781: Allow running on `push` event
**Is your feature request related to a problem? Please describe.**

When trying to run the workflow on `push` event, it gives the error saying only pull_request is supported.

**Describe the solution you'd like**

Can you also allow running it on push? Since a push event will also have changed files.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by harryzcy**
Diff all commits that's pushed using this API: https://octokit.github.io/rest.js/v20#repos-compare-commits-with-basehead

Close #781

### CODE REVIEW

**Review by xalvarez — CHANGES_REQUESTED** [review]
Would this be enough? If I understand correctly only one commit is checked and as far as I know, if you push several commits at once, the push event is triggered only once. So one would actually need to check all commits that were pushed together.

**Comment by harryzcy** [comment]
> Would this be enough? If I understand correctly only one commit is checked and as far as I know, if you push several commits at once, the push event is triggered only once. So one would actually need to check all commits that were pushed together.

Ok, I didn't think about that. I'll make the change

**Comment by xalvarez** [comment]
Thank you very much for your contribution 🙂 it looks promising. I'll have a closer look later.

**Review by xalvarez — APPROVED** [review]
LGTM, I'll prepare a release. Thanks @harryzcy!

**Comment by xalvarez** [comment]
@harryzcy unfortunately I'll need to revert this pull request as on push workflows are failing after squashing and merging pull requests.

**Comment by harryzcy** [comment]
Ok, I'll take a look

**Pull request merged**
